import type { DependencyLicense } from '../../shared/types'
// Generated by scripts/gen-licenses.mjs and bundled, because a packaged app has
// no node_modules to read the notices back out of at runtime.
import generated from './licenses.generated.json'

/** Every third-party package this build ships, sorted by name. */
export function dependencyLicenses(): DependencyLicense[] {
  return generated as DependencyLicense[]
}
