// Emits a `git fast-import` stream for a synthetic repository the size of a
// real corporate monorepo. Written to stdout; `examples/monster-repo.sh` pipes
// it into fast-import.
//
// Why fast-import and not a loop of `git commit`: 140k commits at ~15ms per
// subprocess is over half an hour of pure process spawning. fast-import builds
// the same history in one process, in one packfile, in about a minute.
//
// Every knob is an env var so the shell wrapper can offer presets. Nothing here
// is random — same inputs, same object ids — so two machines building the same
// preset can compare timings on identical repositories.

const num = (name, fallback) => {
  const raw = process.env[name]
  if (raw === undefined || raw === '') return fallback
  const n = Number(raw)
  if (!Number.isFinite(n) || n < 0) throw new Error(`${name} must be a non-negative number, got ${raw}`)
  return Math.floor(n)
}

const CFG = {
  commits: Math.max(1, num('MONSTER_COMMITS', 140000)),
  files: Math.max(1, num('MONSTER_FILES', 92000)),
  sideCommits: num('MONSTER_SIDE_COMMITS', 11000),
  sideBranches: num('MONSTER_SIDE_BRANCHES', 200),
  remoteRefs: num('MONSTER_REMOTE_REFS', 3436),
  tags: num('MONSTER_TAGS', 557),
  localBranches: Math.max(1, num('MONSTER_LOCAL_BRANCHES', 6))
}

// Fixed epoch (2015-01-01) plus a fixed step, so the history spans a plausible
// decade and the dates are identical on every machine.
const T0 = 1420070400
const T_STEP = 180

const AUTHORS = [
  ['Ada Lovelace', 'ada@example.com'],
  ['Grace Hopper', 'grace@example.com'],
  ['Linus Torvalds', 'linus@example.com'],
  ['Margaret Hamilton', 'margaret@example.com'],
  ['Ken Thompson', 'ken@example.com'],
  ['Barbara Liskov', 'barbara@example.com'],
  ['Alan Kay', 'alan@example.com'],
  ['Radia Perlman', 'radia@example.com']
]
const TYPES = ['feat', 'fix', 'refactor', 'perf', 'test', 'docs', 'chore', 'build']

const pad = (n, w) => String(n).padStart(w, '0')

// Spread the files over ~1800 directories rather than one flat pile — a status
// walk over 92k files in a single directory is not the shape any real repo has.
const filePath = (i) => `src/pkg${pad(Math.floor(i / 1000), 3)}/mod${pad(Math.floor((i % 1000) / 50), 2)}/file${pad(i, 6)}.ts`

const fileBody = (i, rev) =>
  `// file ${i}, revision ${rev}\nimport { base } from '../../runtime'\n\n` +
  `export const ID_${i} = ${i}\n\n` +
  `export function transform${i}(input: number): number {\n` +
  `  return base(input) * ${(i % 97) + 1} + ${rev}\n}\n`

// Deterministic stand-in for randomness: which file a given commit touches.
// A plain stride would make every 1000th commit hit the same directory, so mix
// the index through a small LCG first.
const touched = (c) => ((c * 1103515245 + 12345) >>> 8) % CFG.files

// ── Output, with backpressure ─────────────────────────────────────────────────
// A 140k-commit stream is ~40MB. Writing it line by line ignores the pipe's
// high-water mark and balloons memory; batch into ~4MB chunks and wait for drain.
let buf = []
let bufLen = 0
const FLUSH_AT = 4 << 20

const write = (s) => {
  buf.push(s)
  bufLen += s.length
  if (bufLen >= FLUSH_AT) return flush()
  return null
}

const flush = () => {
  if (bufLen === 0) return null
  const chunk = buf.join('')
  buf = []
  bufLen = 0
  return new Promise((resolve, reject) => {
    process.stdout.write(chunk, (err) => (err ? reject(err) : resolve()))
  })
}

const emit = async (s) => {
  const p = write(s)
  if (p) await p
}

// `data` counts bytes, not characters. Everything generated here is ASCII, but
// assert rather than assume — a stray non-ASCII byte would desync the stream
// and fast-import's error message would point nowhere near the cause.
const data = (s) => {
  const bytes = Buffer.byteLength(s, 'utf8')
  if (bytes !== s.length) throw new Error('non-ASCII content in generated stream')
  return `data ${bytes}\n${s}\n`
}

const ident = (mark) => {
  const [name, email] = AUTHORS[mark % AUTHORS.length]
  return `${name} <${email}> ${T0 + mark * T_STEP} +0000`
}

const commitHeader = (ref, mark, msg) =>
  `commit ${ref}\nmark :${mark}\nauthor ${ident(mark)}\ncommitter ${ident(mark)}\n${data(msg)}`

const modify = (fileIndex, rev) =>
  `M 100644 inline ${filePath(fileIndex)}\n${data(fileBody(fileIndex, rev))}`

// ── The history ───────────────────────────────────────────────────────────────

// Root commit: the whole tree in one go. Every later commit touches one file, so
// this is the only place the file count is paid for.
{
  let s = commitHeader('refs/heads/main', 1, 'chore: import vendor tree\n')
  s += `M 100644 inline README.md\n${data(`# monster\n\nSynthetic repository: ${CFG.commits} commits, ${CFG.files} files.\nGenerated by examples/monster-repo.sh - not a real project.\n`)}`
  s += `M 100644 inline .gitignore\n${data('node_modules/\ndist/\n*.log\n')}`
  await emit(s)
  for (let i = 0; i < CFG.files; i++) await emit(modify(i, 0))
}

for (let c = 2; c <= CFG.commits; c++) {
  const f = touched(c)
  const type = TYPES[c % TYPES.length]
  const msg = `${type}: rework transform${f} (#${c})\n`
  await emit(commitHeader('refs/heads/main', c, msg) + modify(f, c))
}

// Side branches carry the commits that are reachable from a remote ref but not
// from HEAD — the gap between `rev-list --count HEAD` and `--all` in a repo
// where nobody prunes merged branches.
const sideHeadMarks = []
if (CFG.sideBranches > 0 && CFG.sideCommits > 0) {
  const per = Math.max(1, Math.floor(CFG.sideCommits / CFG.sideBranches))
  let mark = CFG.commits
  for (let b = 0; b < CFG.sideBranches; b++) {
    const ref = `refs/remotes/origin/feature/branch-${pad(b, 4)}`
    const forkAt = 1 + Math.floor(((b + 1) * CFG.commits) / (CFG.sideBranches + 1))
    for (let k = 0; k < per; k++) {
      mark++
      const f = touched(mark)
      let s = commitHeader(ref, mark, `feat(branch-${pad(b, 4)}): step ${k + 1}\n`)
      if (k === 0) s += `from :${forkAt}\n`
      await emit(s + modify(f, mark))
    }
    sideHeadMarks.push(mark)
  }
}

// The rest of the remote refs are stale pointers into main's history — the
// thousands of never-deleted branches that make `for-each-ref refs/remotes`
// worth measuring.
const spread = (i, total) => 1 + Math.floor(((i + 1) * (CFG.commits - 1)) / (total + 1))

const stale = Math.max(0, CFG.remoteRefs - sideHeadMarks.length)
for (let i = 0; i < stale; i++) {
  await emit(`reset refs/remotes/origin/topic/legacy-${pad(i, 5)}\nfrom :${spread(i, stale)}\n`)
}

// Lightweight tags: a release cadence over the whole history.
for (let i = 0; i < CFG.tags; i++) {
  const major = Math.floor(i / 100)
  await emit(`reset refs/tags/v${major}.${i % 100}.0\nfrom :${spread(i, CFG.tags)}\n`)
}

// Local branches other than main sit near the tip, where a developer's own
// branches actually live.
const LOCAL_NAMES = ['develop', 'release/next', 'hotfix/urgent', 'wip/refactor', 'experiment/perf', 'legacy/maintenance']
for (let i = 0; i < CFG.localBranches - 1; i++) {
  const base = LOCAL_NAMES[i % LOCAL_NAMES.length]
  const name = i < LOCAL_NAMES.length ? base : `${base}-${Math.floor(i / LOCAL_NAMES.length)}`
  const at = Math.max(1, CFG.commits - (i + 1) * 37)
  await emit(`reset refs/heads/${name}\nfrom :${at}\n`)
}

await emit('done\n')
await flush()
